CREATE TABLE "So_Vien_Phi" (
  "MaPhieu" uniqueidentifier NOT NULL CONSTRAINT "DF_d99ea3053e4b8337a1a2aca4f6d" DEFAULT NEWSEQUENTIALID(),
  "MaChiDinh" nvarchar(20),
  "Ngay" smalldatetime,
  "MaBA" nvarchar(20),
  "MaBN" nvarchar(255),
  "Loai" nvarchar(50),
  "MaNV" nvarchar(20),
  "NguoiThu" nvarchar(255),
  "TongTien" float,
  "SoTienHuy" float,
  "Huy" bit,
  "HanBHYT" datetime,
  "SoBHYT" nvarchar(50),
  "NoiDangKyKham" nvarchar(300),
  "TiGiaUSD" float,
  "VAT" float,
  "ConLai" float,
  "MaSoThue" nvarchar(50),
  "LoaiThanhToan" nvarchar(10),
  "TongTienThuoc" float,
  "TongTienBaoHiem" float,
  "BHChi" float,
  "BNTra" float,
  "TienTraLaiBN" float,
  "MaUuDai" nvarchar(20),
  "MaDotKham" nvarchar(30),
  "KetThuc" smallint,
  "uutien" smallint,
  "Chandoan" nvarchar(500),
  CONSTRAINT "PK_d99ea3053e4b8337a1a2aca4f6d" PRIMARY KEY ("MaPhieu")
)